# Generated by Django 3.1.3 on 2021-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Определение', 'verbose_name_plural': 'Определения'},
        ),
        migrations.AddField(
            model_name='task',
            name='themes',
            field=models.CharField(default='Физика', max_length=100, verbose_name='Темы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='theory',
            field=models.TextField(default='Нет', verbose_name='Теория'),
            preserve_default=False,
        ),
    ]
